"""changed score

Revision ID: 1710aa8a243d
Revises: afca400e852f
Create Date: 2023-03-19 15:19:32.086463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1710aa8a243d'
down_revision = 'afca400e852f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamescores', sa.Column('player_id', sa.Integer(), nullable=False))
    op.add_column('gamescores', sa.Column('game_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'gamescores', 'players', ['player_id'], ['tg_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'gamescores', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'players', ['tg_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_constraint(None, 'gamescores', type_='foreignkey')
    op.drop_constraint(None, 'gamescores', type_='foreignkey')
    op.drop_column('gamescores', 'game_id')
    op.drop_column('gamescores', 'player_id')
    # ### end Alembic commands ###
