"""changed creation data default

Revision ID: 17b96eaaf6f7
Revises: 1710aa8a243d
Create Date: 2023-03-19 15:46:23.576983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b96eaaf6f7'
down_revision = '1710aa8a243d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
