"""added unique constraint for game_id&player_id in gamescore

Revision ID: 1a09a66e9cc6
Revises: 872c1633856e
Create Date: 2023-03-19 20:49:48.936741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a09a66e9cc6'
down_revision = '872c1633856e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_player_in_game_score', 'gamescores', ['player_id', 'game_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_player_in_game_score', 'gamescores', type_='unique')
    # ### end Alembic commands ###
