"""changed time back from utcnow

Revision ID: 25d73cfc1014
Revises: 54457ad7bac7
Create Date: 2023-03-19 16:22:25.942947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25d73cfc1014'
down_revision = '54457ad7bac7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
