"""changed creation data default to utcnow

Revision ID: 26680d7452b8
Revises: 17b96eaaf6f7
Create Date: 2023-03-19 16:03:37.746139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26680d7452b8'
down_revision = '17b96eaaf6f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
