"""changed dc

Revision ID: a38eb584302c
Revises: 25d73cfc1014
Create Date: 2023-03-19 17:49:48.426694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38eb584302c'
down_revision = '25d73cfc1014'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
