debug: true
web:
  host: 127.0.0.1
  port: 8000

sentry:
  dsn:
  env: dev

store: {}

# ___ DZ3 ___

user_token: OTY3NmVjYWYtZTJhNC00NzNhLTgwM2YtZGY3OTBkYTM3YWFhXzUxMTM=

session:
  key: CaY5iCkYtN7DqXdiYK1BvmGrQuaSA4Tl4bEk9my0jc0=
admin:
  email: admin@admin.com
  password: admin
database:
  host: 0.0.0.0
  port: 5432
  user: kts_user
  password: kts_pass
  database: kts
bot:
  token: vk1.a.TkqTLu2BVvOEipUxKgjo3jaF5cXaNAl80J_ESSDV2yaeeG66DdYYxoZ928rAxziNpbKhUhdLngfxmqrxRxbKzIquUaP1C9gS8ERN0W0dJX-vnOMdHiWmapsEIuleQxin9wPcgyVIrv3lng4a5yYPs2-WeOYljtleXUfO09mgyJQaYG9eViHgYBioZo7RJ2HBPQsR9IRhbYcoeaEty0QIEg
  group_id: 211873029



